show_message:
  name: Send a page to Divoom Pixoo
  description: Display a specified page on the Divoom Pixoo. Please select the "... Current Page" entity of the device.
  target:
    entity:
      domain: sensor
      integration: divoom_pixoo
  fields:
    page_data:
      name: Page Data
      description: "Consider this as one page, so start at 'page_type=something' (ignore the '-' in front)."
      required: true
      example: "page_type: clock\n enabled: true\n id: 182"
      selector:
        object:
    duration:
      name: Duration of the notification
      description: "This will be the time the message is displayed on the device. Default: the device's scan_time in the config."
      required: false
      example: "10"
      selector:
        number:
          min: 1
          max: 9999
          unit_of_measurement: seconds
          mode: box
play_buzzer:
  name: Play the buzzer on the Divoom Pixoo
  description: Play the buzzer on the Divoom Pixoo. Beware that this maybe could damage the device. Use at your own risk.
  target:
    entity:
      domain: sensor
      integration: divoom_pixoo
  fields:
    buzz_cycle_time_millis:
      name: Buzzing Time per cycle.
      description: "The working time of the buzzer per cycle. The buzzer will not buzz continuously; it will go on and off in cycles (duration in-between not controllable)."
      default: 500
      required: false
      example: "500"
      selector:
          number:
            min: 1
            max: 9999
            unit_of_measurement: milliseconds
            mode: box
    idle_cycle_time_millis:
      name: Idle Time per cycle
      description: "Idle time of the buzzer per cycle."
      default: 500
      required: false
      example: "500"
      selector:
          number:
            min: 1
            max: 9999
            unit_of_measurement: milliseconds
            mode: box
    total_time:
        name: Total Time
        description: "The total time the buzzer will be working."
        default: 3000
        required: false
        example: "3000"
        selector:
            number:
              min: 1
              max: 9999
              unit_of_measurement: milliseconds
              mode: box
